language: python

python: '3.6'
os: linux
dist: xenial

env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

before_install:
  - nvm install v12.18.3
  - ./scripts/ecr_credentials.sh

install:
  - pip3 install -r requirements_travis.txt

before_script:
  - ./scripts/lambdas/install_requirements.sh

script:
  - ./scripts/lambdas/test.sh

after_success:
  - codecov

before_deploy:
  - ./scripts/lambdas/make.sh

deploy:
  - provider: script
    name: "Deploy lambdas"
    script: ./scripts/lambdas/deploy.sh
    skip_cleanup: true
    on:
      branch: master
