language: python

python: '3.6'
os: linux
dist: xenial

env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

before_install:
  - nvm install v12.18.3
  - ./scripts/ecr_credentials.sh

install:
  - pip3 install -r requirements_travis.txt

before_script:
  - make requirements

script:
  - coverage run -m pytest lambdas/fetch_categories
  - coverage run -a -m pytest lambdas/fetch_books_by_category

after_success:
  - codecov

before_deploy:
  - make install

deploy:
  - provider: script
    name: "Deploy fetch_categories"
    script: ./scripts/deploy.sh fetch_categories
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    name: "Deploy fetch_books_by_category"
    script: ./scripts/deploy.sh fetch_categories
    skip_cleanup: true
    on:
      branch: master
