language: python

python: '3.6'
os: linux
dist: xenial

env:
  global:
    - AWS_DEFAULT_REGION=us-west-2
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

before_install:
  - nvm install v12.18.3

install:
  - npm install -g serverless
  - pip3 install -r requirements.txt

script:
  - coverage run -m pytest -vv -r sxX

before_deploy:
  - make

deploy:
  provider: script
  script: serverless deploy --region=us-west-2
  skip_cleanup: true
  on:
    branch: master

