language: python

python: '3.6'
os: linux
dist: xenial

branches:
  only:
    - master

env:
  global:
    - AWS_DEFAULT_REGION=eu-west-2
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

install:
  - pip3 install -r requirements.txt

script:
  - py.test -vv -r sxX


before_deploy:
  - make
  - mv dist/lambda.zip dist/latest.zip
  - cp dist/latest.zip dist/$TRAVIS_COMMIT.zip

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  region: $AWS_BUCKET_REGION
  local_dir: dist
  upload_dir: deployments/lambdas/your_lambda
  acl: private
  cleanup: true
  on:
    all_branches: true
