language: python

python: '3.6'
os: linux
dist: xenial

env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR:$PYTHONPATH

before_install:
  - nvm install v12.18.3
  - ./ecr_credentials.sh

install:
  - pip3 install -r requirements_travis.txt

before_deploy:
  - make

deploy:
  - provider: script
    name: "Deploy fetch_categories"
    script: aws lambda update-function-code --function-name le_libros_fetch_categories --zip-file fileb://lambdas/fetch_categories/dist/lambda.zip
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - codecov --file=lambdas/fetch_categories/.coverage
  - codecov --file=lambdas/fetch_books_by_category/.coverage
