service: leilibros

provider:
  name: aws
  runtime: python3.6

package:
  artifact: dist/lambda.zip

functions:
  categories:
    handler: leilibros.fetch_categories
  books:
    handler: leilibros.fetch_books_by_category